[workspace]
name = "cw-shitstrap"
exclude = [  "scripts/shit-scripts" ]
members =  [
  "contracts/cw-shitstrap",
  "contracts/cw-shitstrap-factory",
  "contracts/cw-shitstrap-ibc-callbacks", 
  "packages/cw-shit-denom", 
  "scripts/shit-scripts",
]
resolver = "2"

[workspace.package]
license = "BSD-3-Clause"
repository = "https://github.com/shitmos/shitstrap"
edition = "2024"
resolver = "2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
panic = 'abort'
rpath = false
# Please do not disable these. Doing so will cause overflow checks in
# all workspace members to stop working. Overflows should be errors.
overflow-checks = true




[workspace.dependencies]
cosmwasm-schema = { path = "../cosmwasm/packages/schema" }
cosmwasm-std  = { path = "../cosmwasm/packages/std" }
cw-storage-plus   = { path = "../cw-storage-plus" }
cw2 = { path = "../cw-minus/packages/cw2" }
cw20 = { path = "../cw-plus/packages/cw20" }
cw20-base = { path = "../cw-plus/contracts/cw20-base" }
dao-interface = {version =  "2.6.0"}
cw-orch = { path = "../cw-orchestrator/cw-orch" }
cw-shitstrap = { path = "contracts/cw-shitstrap"}
cw-shitstrap-factory = { path = "contracts/cw-shitstrap-factory"}
cw-shitstrap-ibc-callbacks = { path = "contracts/cw-shitstrap-ibc-callbacks"}
cw-shit-denom = { path = "packages/cw-shit-denom"}
sha2 = "0.10"
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.58" }
cw-multi-test  = { path = "../cw-multi-test" }
cw-utils = { path = "../cw-minus/packages/cw-utils", version = "3.0.0" }
cw-ownable = { path = "../cw-plus-plus/packages/ownable" }

