[workspace]
name = "cw-shitstrap"
exclude = [ ]
members =  [
  "contracts/cw-shitstrap",
  "contracts/cw-shitstrap-factory", "packages/cw-shit-denom", "scripts/shit-scripts",
]
resolver = "2"

[workspace.package]
license = "BSD-3-Clause"
repository = "https://github.com/shitmos/shitstrap"
edition = "2021"
resolver = "2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
panic = 'abort'
rpath = false
# Please do not disable these. Doing so will cause overflow checks in
# all workspace members to stop working. Overflows should be errors.
overflow-checks = true




[workspace.dependencies]
cosmwasm-schema = "2.3.2"
cosmwasm-std = { version = "2.3.2" }
cw-storage-plus = "2.0.0"
cw2 = "2.0.0"
cw20 = "2.0.0"
cw20-base = "2.0.0"
dao-interface = {version =  "2.6.0"}
cw-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "feat/wasm-path" }
cw-shitstrap = { path = "contracts/cw-shitstrap"}
cw-shitstrap-factory = { path = "contracts/cw-shitstrap-factory"}
cw-shit-denom = { path = "packages/cw-shit-denom"}
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.58" }
cw-multi-test = "2.5.1"
cw-utils = "2.0.0"
cw-ownable = "2.1.0"
