# Auto-generated by gen-tools from cw-shitstrap-factory
# Do not edit manually.

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from typing import Any, List, Optional

cwshitstrapfactory = Any

