/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwShitstrapFactory.types";
import * as _1 from "./CwShitstrapFactory.client";
import * as _2 from "./CwShitstrapFactory.message-composer";
import * as _3 from "./CwShitstrap.types";
import * as _4 from "./CwShitstrap.client";
import * as _5 from "./CwShitstrap.message-composer";
import * as _6 from "./baseClient";
export namespace contracts {
  export const CwShitstrapFactory = {
    ..._0,
    ..._1,
    ..._2
  };
  export const CwShitstrap = {
    ..._3,
    ..._4,
    ..._5
  };
  export const baseClient = {
    ..._6
  };
}