// Auto-generated by gen-tools from cw-shitstrap schema
import type { CwShitstrap } from './CwShitstrap.types';
import type { Coin } from '@cosmjs/amino';

export class CwShitstrapMsgComposer {
  readonly contractAddress: string;

  constructor(contractAddress: string) {
    this.contractAddress = contractAddress;
  }

}
