/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { Uint128, UncheckedDenom, Addr, InstantiateMsg, PossibleShit, DaoParams, ExecuteMsg, Binary, AssetUnchecked, Cw20ReceiveMsg, QueryMsg, CheckedDenom, Config, Boolean, NullableArrayOfPossibleShit } from "./CwShitstrap.types";
export interface CwShitstrapReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  hasShit: () => Promise<Uint128>;
  toShit: () => Promise<Uint128>;
  fullOfShit: () => Promise<Boolean>;
  shitRate: ({
    asset
  }: {
    asset: string;
  }) => Promise<Uint128>;
  shitRates: () => Promise<NullableArrayOfPossibleShit>;
}
export class CwShitstrapQueryClient implements CwShitstrapReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.hasShit = this.hasShit.bind(this);
    this.toShit = this.toShit.bind(this);
    this.fullOfShit = this.fullOfShit.bind(this);
    this.shitRate = this.shitRate.bind(this);
    this.shitRates = this.shitRates.bind(this);
  }
  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  hasShit = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      has_shit: {}
    });
  };
  toShit = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      to_shit: {}
    });
  };
  fullOfShit = async (): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      full_of_shit: {}
    });
  };
  shitRate = async ({
    asset
  }: {
    asset: string;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      shit_rate: {
        asset
      }
    });
  };
  shitRates = async (): Promise<NullableArrayOfPossibleShit> => {
    return this.client.queryContractSmart(this.contractAddress, {
      shit_rates: {}
    });
  };
}
export interface CwShitstrapInterface extends CwShitstrapReadOnlyInterface {
  contractAddress: string;
  sender: string;
  shitStrap: ({
    dao,
    shit
  }: {
    dao?: Addr;
    shit: AssetUnchecked;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  flush: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  refundShitter: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class CwShitstrapClient extends CwShitstrapQueryClient implements CwShitstrapInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.shitStrap = this.shitStrap.bind(this);
    this.flush = this.flush.bind(this);
    this.receive = this.receive.bind(this);
    this.refundShitter = this.refundShitter.bind(this);
  }
  shitStrap = async ({
    dao,
    shit
  }: {
    dao?: Addr;
    shit: AssetUnchecked;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      shit_strap: {
        dao,
        shit
      }
    }, fee_, memo_, funds_);
  };
  flush = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      flush: {}
    }, fee_, memo_, funds_);
  };
  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee_, memo_, funds_);
  };
  refundShitter = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      refund_shitter: {}
    }, fee_, memo_, funds_);
  };
}