/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@interchainjs/types";
import { EncodeObject } from "@interchainjs/cosmos-types";
import { MsgExecuteContract } from "interchainjs/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@interchainjs/encoding";
import { Uint128, UncheckedDenom, Addr, InstantiateMsg, PossibleShit, DaoParams, ExecuteMsg, Binary, AssetUnchecked, Cw20ReceiveMsg, QueryMsg, CheckedDenom, Config, Boolean, NullableArrayOfPossibleShit } from "./CwShitstrap.types";
export interface CwShitstrapMsg {
  contractAddress: string;
  sender: string;
  shitStrap: ({
    dao,
    shit
  }: {
    dao?: Addr;
    shit: AssetUnchecked;
  }, funds_?: Coin[]) => EncodeObject;
  flush: (funds_?: Coin[]) => EncodeObject;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, funds_?: Coin[]) => EncodeObject;
  refundShitter: (funds_?: Coin[]) => EncodeObject;
}
export class CwShitstrapMsgComposer implements CwShitstrapMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.shitStrap = this.shitStrap.bind(this);
    this.flush = this.flush.bind(this);
    this.receive = this.receive.bind(this);
    this.refundShitter = this.refundShitter.bind(this);
  }
  shitStrap = ({
    dao,
    shit
  }: {
    dao?: Addr;
    shit: AssetUnchecked;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          shit_strap: {
            dao,
            shit
          }
        })),
        funds: funds_
      })
    };
  };
  flush = (funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          flush: {}
        })),
        funds: funds_
      })
    };
  };
  receive = ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          receive: {
            amount,
            msg,
            sender
          }
        })),
        funds: funds_
      })
    };
  };
  refundShitter = (funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          refund_shitter: {}
        })),
        funds: funds_
      })
    };
  };
}