/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Uint128, UncheckedDenom, Addr, Action, Expiration, Timestamp, Uint64, PossibleShit, DaoParams, QueryMsg, ArrayOfShitstrapContract, ShitstrapContract, OwnershipForAddr } from "./CwShitstrapFactory.types";
export interface CwShitstrapFactoryReadOnlyInterface {
  contractAddress: string;
  listShitstrapContracts: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfShitstrapContract>;
  listShitstrapContractsReverse: ({
    limit,
    startBefore
  }: {
    limit?: number;
    startBefore?: string;
  }) => Promise<ArrayOfShitstrapContract>;
  listShitstrapContractsByInstantiator: ({
    instantiator,
    limit,
    startAfter
  }: {
    instantiator: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfShitstrapContract>;
  listShitstrapContractsByInstantiatorReverse: ({
    instantiator,
    limit,
    startBefore
  }: {
    instantiator: string;
    limit?: number;
    startBefore?: string;
  }) => Promise<ArrayOfShitstrapContract>;
  listShitstrapContractsByToken: ({
    limit,
    recipient,
    startAfter
  }: {
    limit?: number;
    recipient: string;
    startAfter?: string;
  }) => Promise<ArrayOfShitstrapContract>;
  listShitstrapContractsByTokenReverse: ({
    limit,
    recipient,
    startBefore
  }: {
    limit?: number;
    recipient: string;
    startBefore?: string;
  }) => Promise<ArrayOfShitstrapContract>;
  ownership: () => Promise<OwnershipForAddr>;
  codeId: () => Promise<Uint64>;
}
export class CwShitstrapFactoryQueryClient implements CwShitstrapFactoryReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.listShitstrapContracts = this.listShitstrapContracts.bind(this);
    this.listShitstrapContractsReverse = this.listShitstrapContractsReverse.bind(this);
    this.listShitstrapContractsByInstantiator = this.listShitstrapContractsByInstantiator.bind(this);
    this.listShitstrapContractsByInstantiatorReverse = this.listShitstrapContractsByInstantiatorReverse.bind(this);
    this.listShitstrapContractsByToken = this.listShitstrapContractsByToken.bind(this);
    this.listShitstrapContractsByTokenReverse = this.listShitstrapContractsByTokenReverse.bind(this);
    this.ownership = this.ownership.bind(this);
    this.codeId = this.codeId.bind(this);
  }
  listShitstrapContracts = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfShitstrapContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_shitstrap_contracts: {
        limit,
        start_after: startAfter
      }
    });
  };
  listShitstrapContractsReverse = async ({
    limit,
    startBefore
  }: {
    limit?: number;
    startBefore?: string;
  }): Promise<ArrayOfShitstrapContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_shitstrap_contracts_reverse: {
        limit,
        start_before: startBefore
      }
    });
  };
  listShitstrapContractsByInstantiator = async ({
    instantiator,
    limit,
    startAfter
  }: {
    instantiator: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfShitstrapContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_shitstrap_contracts_by_instantiator: {
        instantiator,
        limit,
        start_after: startAfter
      }
    });
  };
  listShitstrapContractsByInstantiatorReverse = async ({
    instantiator,
    limit,
    startBefore
  }: {
    instantiator: string;
    limit?: number;
    startBefore?: string;
  }): Promise<ArrayOfShitstrapContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_shitstrap_contracts_by_instantiator_reverse: {
        instantiator,
        limit,
        start_before: startBefore
      }
    });
  };
  listShitstrapContractsByToken = async ({
    limit,
    recipient,
    startAfter
  }: {
    limit?: number;
    recipient: string;
    startAfter?: string;
  }): Promise<ArrayOfShitstrapContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_shitstrap_contracts_by_token: {
        limit,
        recipient,
        start_after: startAfter
      }
    });
  };
  listShitstrapContractsByTokenReverse = async ({
    limit,
    recipient,
    startBefore
  }: {
    limit?: number;
    recipient: string;
    startBefore?: string;
  }): Promise<ArrayOfShitstrapContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_shitstrap_contracts_by_token_reverse: {
        limit,
        recipient,
        start_before: startBefore
      }
    });
  };
  ownership = async (): Promise<OwnershipForAddr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership: {}
    });
  };
  codeId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      code_id: {}
    });
  };
}
export interface CwShitstrapFactoryInterface extends CwShitstrapFactoryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createNativeShitStrapContract: ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateCodeId: ({
    shitstrapCodeId
  }: {
    shitstrapCodeId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateOwnership: (action: Action, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class CwShitstrapFactoryClient extends CwShitstrapFactoryQueryClient implements CwShitstrapFactoryInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createNativeShitStrapContract = this.createNativeShitStrapContract.bind(this);
    this.updateCodeId = this.updateCodeId.bind(this);
    this.updateOwnership = this.updateOwnership.bind(this);
  }
  createNativeShitStrapContract = async ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_native_shit_strap_contract: {
        instantiate_msg: instantiateMsg,
        label
      }
    }, fee_, memo_, funds_);
  };
  updateCodeId = async ({
    shitstrapCodeId
  }: {
    shitstrapCodeId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_code_id: {
        shitstrap_code_id: shitstrapCodeId
      }
    }, fee_, memo_, funds_);
  };
  updateOwnership = async (action: Action, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_ownership: action
    }, fee_, memo_, funds_);
  };
}