// Auto-generated by gen-tools from cw-shitstrap schema
import type { cw-shitstrap as CwShitstrapType } from './CwShitstrap.types';
import type { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';

export interface CwShitstrapQueryClient {
  readonly client: CosmWasmClient;
  readonly contractAddress: string;

}

export interface CwShitstrapExecuteClient {
  readonly client: SigningCosmWasmClient;
  readonly contractAddress: string;
  readonly sender: string;

}
