/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@interchainjs/types";
import { EncodeObject } from "@interchainjs/cosmos-types";
import { MsgExecuteContract } from "interchainjs/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@interchainjs/encoding";
import { InstantiateMsg, ExecuteMsg, Uint128, UncheckedDenom, Addr, Action, Expiration, Timestamp, Uint64, PossibleShit, DaoParams, QueryMsg, ArrayOfShitstrapContract, ShitstrapContract, OwnershipForAddr } from "./CwShitstrapFactory.types";
export interface CwShitstrapFactoryMsg {
  contractAddress: string;
  sender: string;
  createNativeShitStrapContract: ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, funds_?: Coin[]) => EncodeObject;
  updateCodeId: ({
    shitstrapCodeId
  }: {
    shitstrapCodeId: number;
  }, funds_?: Coin[]) => EncodeObject;
  updateOwnership: (action: Action, funds_?: Coin[]) => EncodeObject;
}
export class CwShitstrapFactoryMsgComposer implements CwShitstrapFactoryMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createNativeShitStrapContract = this.createNativeShitStrapContract.bind(this);
    this.updateCodeId = this.updateCodeId.bind(this);
    this.updateOwnership = this.updateOwnership.bind(this);
  }
  createNativeShitStrapContract = ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_native_shit_strap_contract: {
            instantiate_msg: instantiateMsg,
            label
          }
        })),
        funds: funds_
      })
    };
  };
  updateCodeId = ({
    shitstrapCodeId
  }: {
    shitstrapCodeId: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_code_id: {
            shitstrap_code_id: shitstrapCodeId
          }
        })),
        funds: funds_
      })
    };
  };
  updateOwnership = (action: Action, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_ownership: action
        })),
        funds: funds_
      })
    };
  };
}