// Auto-generated by gen-tools from cw-shitstrap-factory schema
import type { CwShitstrapFactory } from './CwShitstrapFactory.types';
import type { Coin } from '@cosmjs/amino';

export class CwShitstrapFactoryMsgComposer {
  readonly contractAddress: string;

  constructor(contractAddress: string) {
    this.contractAddress = contractAddress;
  }

}
