// Auto-generated by gen-tools from cw-shitstrap-factory schema
import type { cw-shitstrap-factory as CwShitstrapFactoryType } from './CwShitstrapFactory.types';
import type { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';

export interface CwShitstrapFactoryQueryClient {
  readonly client: CosmWasmClient;
  readonly contractAddress: string;

}

export interface CwShitstrapFactoryExecuteClient {
  readonly client: SigningCosmWasmClient;
  readonly contractAddress: string;
  readonly sender: string;

}
